---
driver:
  name: docker
  port: 2222

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: fedora-21
    driver_config:
      image: fedora:21
  - name: centos-7
    driver_config:
      privileged: true
      run_command: /usr/sbin/init
      use_sudo: false
      image: centos:7
  - name: debian-8
    driver_config:
      image: debian:8

suites:
  - name: aws-codedeploy-agent
    run_list:
      - recipe[aws-codedeploy-agent]
    attributes:
