---
driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  associate_public_ip: true
  aws_ssh_key_id: kitchen-ec2-wortimmo
  security_group_ids: ["sg-2ee82c54"]
  interface: dns

transport:
  ssh_key: ~/.ssh/kitchen-ec2-wortimmo.pem
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: ubuntu-16.04-aws
    driver:
      image_id: ami-4d46d534
      instance_type: t2.micro
  - name: ubuntu-14.04-aws
    driver:
      image_id: ami-d05e75b8
      instance_type: t2.micro
  - name: ubuntu-12.04-aws
    driver:
      image_id: ami-81fb34ea
      instance_type: t2.micro
  - name: debian-8-aws
    driver:
      image_id: ami-8e9ca3e4
      instance_type: t2.micro
    transport:
          username: admin
  - name: centos-7-aws
    driver:
      image_id: ami-6d1c2007
      instance_type: t2.micro
    transport:
          username: centos
  - name: amazon-linux
    driver:
      image_id: ami-1ecae776
      instance_type: t2.micro
    transport:
          username: ec2-user

suites:
  - name: aws-codedeploy-agent
    run_list:
      - recipe[aws-codedeploy-agent]
    attributes:
