---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        # prevent APT from deleting the APT folder
        - RUN rm /etc/apt/apt.conf.d/docker-clean

suites:
  - name: "aws-codedeploy-agent"
    run_list:
      - recipe[aws-codedeploy-agent::default]
    attributes:
